name: Create resources

# Trigger on pushes to main (change branches array if you need other branches)
on:
  push:
    branches:
      - main

jobs:
  create-resources:
    name: Create resources
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ] || [ -f package.json ]; then
            npm ci
          else
            echo "No package.json found, skipping install"
          fi

      - name: Create resources (idempotent)
        run: |
          if npm run | grep -q create-resources; then
            npm run create-resources
          else
            echo "No create-resources script; nothing to do"
          fi
